version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo install dependencies
      - npm install
  build:
    commands:
      - echo run the tests
      - npm test
artifacts:
  files:
    - 'cypress/reports/html/**/*'
  discard-paths: yes
