version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.3

jobs:
  cypress-run:
    docker:
      - image: cimg/node:22.0
    steps:
      - checkout

      - browser-tools/install-chrome
      
      - run:
          name: Install dependencies
          command: npm install
      
      - run:
          name: Run Cypress tests
          command: npm test
      
      - store_artifacts:
          path: cypress/reports/html
          destination: cypress-test-results

workflows:
  version: 2
  cypress_tests:
    jobs:
      - cypress-run
